from NumericSolve import one_d_diffur as NumericSolver1d, two_d_diffur as NumericSolver2d

# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QGridLayout, QWidget, QTableWidget, QTableWidgetItem

from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 502)
        self.cw = QtWidgets.QWidget(MainWindow)
        self.cw.setObjectName("cw")
        self.tabWidget = QtWidgets.QTabWidget(self.cw)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.tabWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.startc_0 = QtWidgets.QGroupBox(self.tab_0)
        self.startc_0.setGeometry(QtCore.QRect(20, 10, 151, 81))
        self.startc_0.setObjectName("startc_0")
        self.u0txt_0 = QtWidgets.QLabel(self.startc_0)
        self.u0txt_0.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.u0txt_0.setFont(font)
        self.u0txt_0.setObjectName("u0txt_0")
        self.x0txt_0 = QtWidgets.QLabel(self.startc_0)
        self.x0txt_0.setGeometry(QtCore.QRect(10, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x0txt_0.setFont(font)
        self.x0txt_0.setObjectName("x0txt_0")
        self.u0_0 = QtWidgets.QLineEdit(self.startc_0)
        self.u0_0.setGeometry(QtCore.QRect(50, 20, 81, 21))
        self.u0_0.setObjectName("u0_0")
        self.x0_0 = QtWidgets.QLineEdit(self.startc_0)
        self.x0_0.setGeometry(QtCore.QRect(50, 50, 81, 21))
        self.x0_0.setObjectName("x0_0")
        self.table_0 = QtWidgets.QTableWidget(self.tab_0)
        self.table_0.setGeometry(QtCore.QRect(10, 240, 611, 192))
        self.table_0.setObjectName("table_0")
        self.table_0.setColumnCount(11)
        self.table_0.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_0.setHorizontalHeaderItem(10, item)
        self.table_0.horizontalHeader().setDefaultSectionSize(55)
        self.count_0 = QtWidgets.QGroupBox(self.tab_0)
        self.count_0.setGeometry(QtCore.QRect(20, 100, 431, 81))
        self.count_0.setObjectName("count_0")
        self.ntxt_0 = QtWidgets.QLabel(self.count_0)
        self.ntxt_0.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ntxt_0.setFont(font)
        self.ntxt_0.setObjectName("ntxt_0")
        self.etxt_0 = QtWidgets.QLabel(self.count_0)
        self.etxt_0.setGeometry(QtCore.QRect(10, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etxt_0.setFont(font)
        self.etxt_0.setObjectName("etxt_0")
        self.n_0 = QtWidgets.QLineEdit(self.count_0)
        self.n_0.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.n_0.setObjectName("n_0")
        self.e_0 = QtWidgets.QLineEdit(self.count_0)
        self.e_0.setGeometry(QtCore.QRect(80, 50, 81, 21))
        self.e_0.setObjectName("e_0")
        self.lefttxt_0 = QtWidgets.QLabel(self.count_0)
        self.lefttxt_0.setGeometry(QtCore.QRect(180, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lefttxt_0.setFont(font)
        self.lefttxt_0.setObjectName("lefttxt_0")
        self.left_0 = QtWidgets.QLineEdit(self.count_0)
        self.left_0.setGeometry(QtCore.QRect(320, 20, 81, 21))
        self.left_0.setObjectName("left_0")
        self.step_0 = QtWidgets.QGroupBox(self.tab_0)
        self.step_0.setGeometry(QtCore.QRect(190, 10, 261, 81))
        self.step_0.setObjectName("step_0")
        self.control_0 = QtWidgets.QRadioButton(self.step_0)
        self.control_0.setGeometry(QtCore.QRect(10, 20, 261, 17))
        self.control_0.setChecked(True)
        self.control_0.setObjectName("control_0")
        self.h_0 = QtWidgets.QLineEdit(self.step_0)
        self.h_0.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.h_0.setObjectName("h_0")
        self.htxt_0 = QtWidgets.QLabel(self.step_0)
        self.htxt_0.setGeometry(QtCore.QRect(10, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.htxt_0.setFont(font)
        self.htxt_0.setObjectName("htxt_0")
        self.startbutton_0 = QtWidgets.QPushButton(self.tab_0)
        self.startbutton_0.setGeometry(QtCore.QRect(470, 110, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startbutton_0.setFont(font)
        self.startbutton_0.setObjectName("startbutton_0")
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.count_1 = QtWidgets.QGroupBox(self.tab_1)
        self.count_1.setGeometry(QtCore.QRect(20, 100, 431, 81))
        self.count_1.setObjectName("count_1")
        self.ntxt_1 = QtWidgets.QLabel(self.count_1)
        self.ntxt_1.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ntxt_1.setFont(font)
        self.ntxt_1.setObjectName("ntxt_1")
        self.etxt_1 = QtWidgets.QLabel(self.count_1)
        self.etxt_1.setGeometry(QtCore.QRect(10, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etxt_1.setFont(font)
        self.etxt_1.setObjectName("etxt_1")
        self.n_1 = QtWidgets.QLineEdit(self.count_1)
        self.n_1.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.n_1.setObjectName("n_1")
        self.e_1 = QtWidgets.QLineEdit(self.count_1)
        self.e_1.setGeometry(QtCore.QRect(80, 50, 81, 21))
        self.e_1.setObjectName("e_1")
        self.lefttxt_1 = QtWidgets.QLabel(self.count_1)
        self.lefttxt_1.setGeometry(QtCore.QRect(180, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lefttxt_1.setFont(font)
        self.lefttxt_1.setObjectName("lefttxt_1")
        self.left_1 = QtWidgets.QLineEdit(self.count_1)
        self.left_1.setGeometry(QtCore.QRect(320, 20, 81, 21))
        self.left_1.setObjectName("left_1")
        self.startc_1 = QtWidgets.QGroupBox(self.tab_1)
        self.startc_1.setGeometry(QtCore.QRect(20, 10, 151, 81))
        self.startc_1.setObjectName("startc_1")
        self.u0txt_1 = QtWidgets.QLabel(self.startc_1)
        self.u0txt_1.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.u0txt_1.setFont(font)
        self.u0txt_1.setObjectName("u0txt_1")
        self.x0txt_1 = QtWidgets.QLabel(self.startc_1)
        self.x0txt_1.setGeometry(QtCore.QRect(10, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x0txt_1.setFont(font)
        self.x0txt_1.setObjectName("x0txt_1")
        self.u0_1 = QtWidgets.QLineEdit(self.startc_1)
        self.u0_1.setGeometry(QtCore.QRect(50, 20, 81, 21))
        self.u0_1.setObjectName("u0_1")
        self.x0_1 = QtWidgets.QLineEdit(self.startc_1)
        self.x0_1.setGeometry(QtCore.QRect(50, 50, 81, 21))
        self.x0_1.setObjectName("x0_1")
        self.table_1 = QtWidgets.QTableWidget(self.tab_1)
        self.table_1.setGeometry(QtCore.QRect(10, 240, 611, 192))
        self.table_1.setObjectName("table_1")
        self.table_1.setColumnCount(9)
        self.table_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(8, item)
        self.table_1.horizontalHeader().setDefaultSectionSize(67)
        self.table_1.horizontalHeader().setMinimumSectionSize(39)
        self.step_1 = QtWidgets.QGroupBox(self.tab_1)
        self.step_1.setGeometry(QtCore.QRect(190, 10, 261, 81))
        self.step_1.setObjectName("step_1")
        self.control_1 = QtWidgets.QRadioButton(self.step_1)
        self.control_1.setGeometry(QtCore.QRect(10, 20, 261, 17))
        self.control_1.setChecked(True)
        self.control_1.setObjectName("control_1")
        self.h_1 = QtWidgets.QLineEdit(self.step_1)
        self.h_1.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.h_1.setObjectName("h_1")
        self.htxt_1 = QtWidgets.QLabel(self.step_1)
        self.htxt_1.setGeometry(QtCore.QRect(10, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.htxt_1.setFont(font)
        self.htxt_1.setObjectName("htxt_1")
        self.startbutton_1 = QtWidgets.QPushButton(self.tab_1)
        self.startbutton_1.setGeometry(QtCore.QRect(470, 110, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startbutton_1.setFont(font)
        self.startbutton_1.setObjectName("startbutton_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.startc_2 = QtWidgets.QGroupBox(self.tab_2)
        self.startc_2.setGeometry(QtCore.QRect(20, 10, 151, 91))
        self.startc_2.setObjectName("startc_2")
        self.u0txt_2 = QtWidgets.QLabel(self.startc_2)
        self.u0txt_2.setGeometry(QtCore.QRect(20, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.u0txt_2.setFont(font)
        self.u0txt_2.setObjectName("u0txt_2")
        self.x0txt_2 = QtWidgets.QLabel(self.startc_2)
        self.x0txt_2.setGeometry(QtCore.QRect(20, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x0txt_2.setFont(font)
        self.x0txt_2.setObjectName("x0txt_2")
        self.u0_2 = QtWidgets.QLineEdit(self.startc_2)
        self.u0_2.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.u0_2.setObjectName("u0_2")
        self.x0_2 = QtWidgets.QLineEdit(self.startc_2)
        self.x0_2.setGeometry(QtCore.QRect(60, 40, 71, 16))
        self.x0_2.setObjectName("x0_2")
        self.z0txt_2 = QtWidgets.QLabel(self.startc_2)
        self.z0txt_2.setGeometry(QtCore.QRect(20, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z0txt_2.setFont(font)
        self.z0txt_2.setObjectName("z0txt_2")
        self.z0_2 = QtWidgets.QLineEdit(self.startc_2)
        self.z0_2.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.z0_2.setObjectName("z0_2")
        self.table_2 = QtWidgets.QTableWidget(self.tab_2)
        self.table_2.setGeometry(QtCore.QRect(10, 240, 611, 192))
        self.table_2.setObjectName("table_2")
        self.table_2.setColumnCount(9)
        self.table_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(8, item)
        self.table_2.horizontalHeader().setDefaultSectionSize(67)
        self.table_2.horizontalHeader().setMinimumSectionSize(39)
        self.step_2 = QtWidgets.QGroupBox(self.tab_2)
        self.step_2.setGeometry(QtCore.QRect(190, 10, 261, 81))
        self.step_2.setObjectName("step_2")
        self.control_2 = QtWidgets.QRadioButton(self.step_2)
        self.control_2.setEnabled(True)
        self.control_2.setGeometry(QtCore.QRect(10, 20, 261, 17))
        self.control_2.setChecked(True)
        self.control_2.setObjectName("control_2")
        self.h_2 = QtWidgets.QLineEdit(self.step_2)
        self.h_2.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.h_2.setObjectName("h_2")
        self.htxt_2 = QtWidgets.QLabel(self.step_2)
        self.htxt_2.setGeometry(QtCore.QRect(10, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.htxt_2.setFont(font)
        self.htxt_2.setObjectName("htxt_2")
        self.count_2 = QtWidgets.QGroupBox(self.tab_2)
        self.count_2.setGeometry(QtCore.QRect(20, 100, 431, 81))
        self.count_2.setObjectName("count_2")
        self.ntxt_2 = QtWidgets.QLabel(self.count_2)
        self.ntxt_2.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ntxt_2.setFont(font)
        self.ntxt_2.setObjectName("ntxt_2")
        self.etxt_2 = QtWidgets.QLabel(self.count_2)
        self.etxt_2.setGeometry(QtCore.QRect(10, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etxt_2.setFont(font)
        self.etxt_2.setObjectName("etxt_2")
        self.n_2 = QtWidgets.QLineEdit(self.count_2)
        self.n_2.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.n_2.setObjectName("n_2")
        self.e_2 = QtWidgets.QLineEdit(self.count_2)
        self.e_2.setGeometry(QtCore.QRect(80, 50, 81, 21))
        self.e_2.setObjectName("e_2")
        self.lefttxt_2 = QtWidgets.QLabel(self.count_2)
        self.lefttxt_2.setGeometry(QtCore.QRect(180, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lefttxt_2.setFont(font)
        self.lefttxt_2.setObjectName("lefttxt_2")
        self.left_2 = QtWidgets.QLineEdit(self.count_2)
        self.left_2.setGeometry(QtCore.QRect(320, 20, 81, 21))
        self.left_2.setObjectName("left_2")
        self.parameters_2 = QtWidgets.QGroupBox(self.tab_2)
        self.parameters_2.setGeometry(QtCore.QRect(470, 10, 151, 81))
        self.parameters_2.setObjectName("parameters_2")
        self.atxt_2 = QtWidgets.QLabel(self.parameters_2)
        self.atxt_2.setGeometry(QtCore.QRect(10, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.atxt_2.setFont(font)
        self.atxt_2.setObjectName("atxt_2")
        self.a_2 = QtWidgets.QLineEdit(self.parameters_2)
        self.a_2.setGeometry(QtCore.QRect(40, 40, 81, 21))
        self.a_2.setObjectName("a_2")
        self.startbutton_2 = QtWidgets.QPushButton(self.tab_2)
        self.startbutton_2.setGeometry(QtCore.QRect(470, 110, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startbutton_2.setFont(font)
        self.startbutton_2.setObjectName("startbutton_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.cw)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выбор параметров"))
        self.startc_0.setTitle(_translate("MainWindow", "Начальное состояние"))
        self.u0txt_0.setText(_translate("MainWindow", "U₀="))
        self.x0txt_0.setText(_translate("MainWindow", "X₀="))
        self.u0_0.setText(_translate("MainWindow", "1"))
        self.x0_0.setText(_translate("MainWindow", "1"))
        item = self.table_0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "i"))
        item = self.table_0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "xᵢ"))
        item = self.table_0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "vᵢ"))
        item = self.table_0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "v2ᵢ"))
        item = self.table_0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "|vᵢ-v2ᵢ|"))
        item = self.table_0.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ОЛП"))
        item = self.table_0.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "hᵢ"))
        item = self.table_0.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "C1"))
        item = self.table_0.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C2"))
        item = self.table_0.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "uᵢ"))
        item = self.table_0.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "|uᵢ-vᵢ|"))
        self.count_0.setTitle(_translate("MainWindow", "Счёт"))
        self.ntxt_0.setText(_translate("MainWindow", "N max="))
        self.etxt_0.setText(_translate("MainWindow", "ε гран.="))
        self.n_0.setText(_translate("MainWindow", "500"))
        self.e_0.setText(_translate("MainWindow", "1e-6"))
        self.lefttxt_0.setText(_translate("MainWindow", "Правая граница ="))
        self.left_0.setText(_translate("MainWindow", "10"))
        self.step_0.setTitle(_translate("MainWindow", "Шаг"))
        self.control_0.setText(_translate("MainWindow", "Решать с контролем локальной погрешности"))
        self.h_0.setText(_translate("MainWindow", "0.01"))
        self.htxt_0.setText(_translate("MainWindow", "h начальное="))
        self.startbutton_0.setText(_translate("MainWindow", "Пуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Тестовая задача"))
        self.count_1.setTitle(_translate("MainWindow", "Счёт"))
        self.ntxt_1.setText(_translate("MainWindow", "N max="))
        self.etxt_1.setText(_translate("MainWindow", "ε гран.="))
        self.n_1.setText(_translate("MainWindow", "500"))
        self.e_1.setText(_translate("MainWindow", "1e-6"))
        self.lefttxt_1.setText(_translate("MainWindow", "Правая граница ="))
        self.left_1.setText(_translate("MainWindow", "10"))
        self.startc_1.setTitle(_translate("MainWindow", "Начальное состояние"))
        self.u0txt_1.setText(_translate("MainWindow", "U₀="))
        self.x0txt_1.setText(_translate("MainWindow", "X₀="))
        self.u0_1.setText(_translate("MainWindow", "1"))
        self.x0_1.setText(_translate("MainWindow", "1"))
        item = self.table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "i"))
        item = self.table_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "xᵢ"))
        item = self.table_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "vᵢ"))
        item = self.table_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "v2ᵢ"))
        item = self.table_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "|vᵢ-v2ᵢ|"))
        item = self.table_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ОЛП"))
        item = self.table_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "hᵢ"))
        item = self.table_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "C1"))
        item = self.table_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C2"))
        self.step_1.setTitle(_translate("MainWindow", "Шаг"))
        self.control_1.setText(_translate("MainWindow", "Решать с контролем локальной погрешности"))
        self.h_1.setText(_translate("MainWindow", "0.01"))
        self.htxt_1.setText(_translate("MainWindow", "h начальное="))
        self.startbutton_1.setText(_translate("MainWindow", "Пуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Задача 1"))
        self.startc_2.setTitle(_translate("MainWindow", "Начальное состояние"))
        self.u0txt_2.setText(_translate("MainWindow", "U₀="))
        self.x0txt_2.setText(_translate("MainWindow", "X₀="))
        self.u0_2.setText(_translate("MainWindow", "1"))
        self.x0_2.setText(_translate("MainWindow", "1"))
        self.z0txt_2.setText(_translate("MainWindow", "Z₀="))
        self.z0_2.setText(_translate("MainWindow", "1"))
        item = self.table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "i"))
        item = self.table_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "xᵢ"))
        item = self.table_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "vᵢ"))
        item = self.table_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "v2ᵢ"))
        item = self.table_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "|vᵢ-v2ᵢ|"))
        item = self.table_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ОЛП"))
        item = self.table_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "hᵢ"))
        item = self.table_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "C1"))
        item = self.table_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C2"))
        self.step_2.setTitle(_translate("MainWindow", "Шаг"))
        self.control_2.setText(_translate("MainWindow", "Решать с контролем локальной погрешности"))
        self.h_2.setText(_translate("MainWindow", "0.01"))
        self.htxt_2.setText(_translate("MainWindow", "h начальное="))
        self.count_2.setTitle(_translate("MainWindow", "Счёт"))
        self.ntxt_2.setText(_translate("MainWindow", "N max="))
        self.etxt_2.setText(_translate("MainWindow", "ε гран.="))
        self.n_2.setText(_translate("MainWindow", "500"))
        self.e_2.setText(_translate("MainWindow", "1e-6"))
        self.lefttxt_2.setText(_translate("MainWindow", "Правая граница ="))
        self.left_2.setText(_translate("MainWindow", "10"))
        self.parameters_2.setTitle(_translate("MainWindow", "Параметры"))
        self.atxt_2.setText(_translate("MainWindow", "a="))
        self.a_2.setText(_translate("MainWindow", "1"))
        self.startbutton_2.setText(_translate("MainWindow", "Пуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Задача 2"))

    def add_functions(self):
        self.startbutton_0.clicked.connect(lambda: self.work(0))
        self.startbutton_1.clicked.connect(lambda: self.work(1))
        self.startbutton_2.clicked.connect(lambda: self.work(2))

    def getparameters(self, task):
        data = {
            "z0": 0.,
            "x0": 1.,
            "u0": 1.,
            "Nmax": 500,
            "eps": 1e-6,
            "control": True,
            "left": 10.,
            "h": 0.01,
            'a': 1.0}  # дефолтные значения. Эта строчка не так нужна, но я захотел менять дефолтную дату, а не создавать разные
        if task == 0:
            data["x0"] = float(self.x0_0.text())
            data["u0"] = float(self.u0_0.text())
            data["Nmax"] = int(self.n_0.text())
            data["eps"] = float(self.e_0.text())
            data["control"] = bool(self.control_0.isChecked())
            data["h"] = float(self.h_0.text())
            data["left"] = float(self.left_0.text())
        if task == 1:
            data["x0"] = float(self.x0_1.text())
            data["u0"] = float(self.u0_1.text())
            data["Nmax"] = int(self.n_1.text())
            data["eps"] = float(self.e_1.text())
            data["control"] = bool(self.control_1.isChecked())
            data["h"] = float(self.h_1.text())
            data["left"] = float(self.left_1.text())
        if task == 2:
            data["z0"] = float(self.z0_2.text())
            data["x0"] = float(self.x0_2.text())
            data["u0"] = float(self.u0_2.text())
            data["Nmax"] = int(self.n_2.text())
            data["eps"] = float(self.e_2.text())
            data["control"] = bool(self.control_2.isChecked())
            data["h"] = float(self.h_2.text())
            data["left"] = float(self.left_2.text())
            data["a"] = float(self.a_2.text())
        return task, data

    def fill_table(self, task, lpcontrol, tabledata):
        if task == 0: table = self.table_0
        elif task == 1: table = self.table_1
        elif task == 2: table = self.table_2

        for i in range(len(tabledata[0])):
            table.showColumn(i)

        table.setRowCount(len(tabledata))
        for i in range(len(tabledata)):
            for j in range(len(tabledata[i])):
                table.setItem(i, j, QTableWidgetItem(str(tabledata[i][j])))
        table.resizeColumnsToContents()
        table.verticalHeader().setVisible(0)
        if task == 1:
            if not lpcontrol:
                table.hideColumn(3)
                table.hideColumn(4)
                table.hideColumn(5)
                table.hideColumn(7)
                table.hideColumn(8)
        elif task == 2:
            table.setHorizontalHeaderItem(4, QTableWidgetItem("|vᵢ-v2ᵢ|"))
            if not lpcontrol:
                #table.hideColumn(4)
                table.hideColumn(6)
                table.hideColumn(5)
                table.hideColumn(7)
                table.hideColumn(8)
                table.setHorizontalHeaderItem(4, QTableWidgetItem("h"))

    def work(self, task):
        parameters = self.getparameters(task)
        data = parameters[1]
        if task == 0:
            ns = NumericSolver1d(category=0, variant_num=1, u0=data["u0"], x0=data["x0"], n_max=data["Nmax"], eps=data["eps"], b=data["left"], h=data["h"], with_lp=data["control"])
            ns.solve(with_lp=data["control"])
            ns.plot_solution()
        elif task == 1:
            ns = NumericSolver1d(category=1, variant_num=1, u0=data["u0"], x0=data["x0"], n_max=data["Nmax"], eps=data["eps"], b=data["left"], h=data["h"], with_lp=data["control"])
            ns.solve(with_lp=data["control"])
            ns.plot_solution()
        elif task == 2:
            ns = NumericSolver2d(u0=data["u0"], x0=data["x0"], z0=data["z0"], n_max=data["Nmax"], eps=data["eps"], a=data["a"], b=data["left"], h=data["h"], with_lp=data["control"])
            ns.solve(with_lp=data["control"])
            ns.plot_solution()
            ns.PlotPhasePortait()
            print(data['control'])
        print(ns.return_table())
        self.fill_table(task, data["control"], ns.return_table())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())

